before_install:
    - yes | sdkmanager "platforms;android-28"
language: android
android:
  components:
    - android-28
    - add-on
    - extra
    - sys-img-x86-android-28
    - sys-img-armeabi-v7a-android-25
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'build-tool.+'
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
